---
title: "Supplementary information for: *Sodium silicate and hexametaphosphate promote the release of (oxyhydr)oxide nanoparticles from corroding iron*"
author: "Benjamin F. Trueman, Javier Locsin, Evelyne Dor&eacute;, Kalli Hood, and Graham A. Gagnon"
date: "Centre for Water Resources Studies,* Department of Civil & Resource Engineering, Dalhousie University, 1360 Barrington St., Halifax, Nova Scotia, Canada B3H 4R2  \n&nbsp;   \n&nbsp;*Corresponding author  \n&nbsp;E-mail: benjamin.trueman@dal.ca    \n&nbsp;Tel:902.494.6070  \n&nbsp;Fax: 902.494.3105"
output:
  word_document:
    keep_md: no
    reference_docx: StylesTemplate.docx
  html_document: default
bibliography: references.bib
csl: environmental-science-and-technology.csl
---

This document contains 1 table and 3 figures.  

```{r setup, include=FALSE}
here::i_am("Rmarkdown/paper-si.Rmd")
knitr::opts_chunk$set(
  echo = FALSE,
  dev = "png",
  dpi = 600,
  fig.width = 3.33,
  fig.height = 4
)
options(dplyr.summarise.inform = FALSE)
palette <- wesanderson::wes_palette("Zissou1", 6, type = "continuous")
```

```{r packages, message=FALSE}
library("tidyverse")
library("fffprocessr")
library("ggtext")
source(here::here("R/functions.R"))
```

```{r theme}
theme_set(
  theme_minimal() + 
    theme(
      legend.position = "bottom",
      legend.margin = margin(r = 1, unit = "cm")
    )
)
```

```{r load, message=FALSE, results="hide"}

c(
  combined = "data/fff_combined.csv",
  mals_data = "data/mals_combined.csv",
  calib_icp = "data/icp_calibration_files_clean.csv",
  direct_quant = "data/icp_direct_quant.csv",
  qc_recovery = "data/qc_recoveries.csv",
  image_j = "data/image_j_clean.csv",
  proteins = "data/proteins_clean.csv",
  pdat = "data/polyp_clean.csv"
) %>% 
  map(~ read_csv(here::here(.x))) %>% 
  list2env(envir = .GlobalEnv)

```

```{r plot-names}

sample_names <- tibble::tribble(
          ~sample,                                                   ~plot_sample,
        "100SiO2",      "Sodium silicate (100 mg SiO<sub>2</sub> L<sup>-1</sup>)",
            "3PP",             "Sodium hexametaphosphate (3 mg P L<sup>-1</sup>)",
 "FeOx-pHcontrol",                                                      "Control",
     "100SiO2+Pb", "Sodium silicate + Pb (100 mg SiO<sub>2</sub> L<sup>-1</sup>)",
         "3PP+Pb",        "Sodium hexametaphosphate + Pb (3 mg P L<sup>-1</sup>)",
        "HM_2ppm",             "Sodium hexametaphosphate (2 mg P L<sup>-1</sup>)",
  "TrimetaP_2ppm",              "Sodium trimetaphosphate (2 mg P L<sup>-1</sup>)"
   )

```

```{r table-s1}
tibble::tribble(
  ~Parameter, ~Value,
  "Injection volume", "50 µL",
  "Spacer", "500 µm",
  "Total run time", "33.5 min",
  "Detector flow", "1 mL min^-1^",
  "Injection flow", "0.2 mL min^-1^",
  "Focus flow", "1.5 mL min^-1^",
  "Focus period", "5 min",
  "Transition period", "1 min",
  "Crossflow", "2 mL min^-1^ ",
) %>% 
  knitr::kable(caption = "**Table S1.** FFF run parameters for globular protein standards.")
```

```{r mals-plot, fig.cap="**Figure S1.** Baseline-corrected multi-angle light scattering data (triplicate sodium hexametaphosphate suspensions)."}

param_mals <- distinct(mals_data, param)$param
striplabs <- str_replace(param_mals, "(ls)(\\d+)", "\\2&deg;")
names(striplabs) <- param_mals
striplabs <- as_labeller(striplabs)

# Plot the data at all 21 angles

plot_mals <- function(suspension) {
  mals_data %>% 
    filter(time > 30, sample == suspension) %>% 
    ggplot(aes(time, conc, group = interaction(date, sample))) + 
    facet_wrap(
      vars(fct_reorder(param, as.numeric(str_extract(param, "\\d+")))),
      labeller = striplabs,
      # scales = "free_y"
    ) + 
    geom_line(size = .3) + 
    theme(
      legend.position = "bottom",
      strip.text = ggtext::element_markdown(),
      axis.text = element_text(size = 5)
    ) +
    labs(
      x = "Retention time (min)",
      y = "Scattering intensity above baseline",
      col = NULL
    )

}

plot_mals("3PP")

```

```{r mals-plot-2, fig.cap="**Figure S2.** Baseline-corrected multi-angle light scattering data (triplicate sodium silicate suspensions)."}
plot_mals("100SiO2")
```

```{r fig-s1, fig.cap="**Figure S3:** Fractograms representing pure solutions of sodium hexameta- and trimeta-phosphate.", fig.height = 2, fig.width = 3.33}

pdat %>%
  left_join(sample_names, by = "sample") %>% 
  filter(time > 10, sample != "blank") %>% 
  ggplot(aes(time, conc, col = plot_sample, group = interaction(date, sample))) + 
  geom_line() + 
  scale_color_manual(values = palette[c(1,4)]) +
  labs(
    x = "Retention time (min.)",
    y = expression("[P] (µg L"^-1*")"),
    col = NULL
  ) + 
  guides(col = guide_legend(nrow = 2)) +
  theme(
    legend.text = ggtext::element_markdown()
  )
  
```

```{r checks, eval=FALSE}

# check that peak broadening is minimal between UV and ICP:

combined %>% 
  filter(
    param %in% c("UV254_2", "57Fe"),
    sample != "FeOx-pHcontrol",
    date < "2021-12-01"
  ) %>% 
  group_by(date, sample, param) %>% 
  mutate(conc = conc / max(conc)) %>% 
  ggplot(aes(time, conc, col =  param, group = interaction(date, param))) + 
  facet_wrap(vars(sample), scales = "free_y") +
  geom_line()

```